# -*- coding: utf-8 -*-
"""Translate PPTX from English/Korean to Simplified Chinese, preserving all formatting."""

from pptx import Presentation
import copy

# Comprehensive translation dictionary: English/Korean text → Simplified Chinese
TRANSLATIONS = {
    # === SLIDE 1 ===
    "CHAPTER 2": "第2章",
    "Python for machine learning": "机器学习中的Python",
    "Python for Machine Learning": "机器学习中的Python",
    "Python language history, basic grammar, data structure, function/class design, performance optimization, development environment": "Python语言历史、基础语法、数据结构、函数/类设计、性能优化、开发环境",
    "Machine learning | Machine Learning": "机器学习 | Machine Learning",

    # === SLIDE 2 ===
    "Table of Contents (Table of Contents) ||| GIL) || |": "目录 ||| GIL) || |",
    "Chapter 2 전체 구성": "第2章 整体结构",
    "Part I: 이론": "第一部分：理论",
    "2.1  왜 Python인가": "2.1  为什么选择Python",
    "2.2  기초 문법 (변수, 연산자, 제어문)": "2.2  基础语法（变量、运算符、控制语句）",
    "2.3  자료구조 심화 (list, tuple, dict, set)": "2.3  数据结构进阶（list、tuple、dict、set）",
    "2.4  함수와 클래스 (sklearn 패턴)": "2.4  函数与类（sklearn模式）",
    "2.5  성능 최적화 (프로파일링, 벡터화, GIL)": "2.5  性能优化（性能分析、向量化、GIL）",
    "2.6  개발환경 (conda, Jupyter, IDE)": "2.6  开发环境（conda、Jupyter、IDE）",
    "Part II: 실습 & 논문": "第二部分：实践 & 论文",
    "2.7   논문 리뷰 (5편)": "2.7   论文综述（5篇）",
    "2.8   실습: Python 프로파일링": "2.8   实践：Python性能分析",
    "2.9   실습: 자료구조 벤치마크": "2.9   实践：数据结构基准测试",
    "2.10  실습: 함수형 프로그래밍 ML": "2.10  实践：函数式编程ML",
    "2.11  End-to-end ML 파이프라인": "2.11  端到端ML流水线",
    "2.12  핵심 요약 + 복습 질문": "2.12  核心总结 + 复习问题",

    # === SLIDE 3 ===
    "Learning Objectives": "学习目标",
    "Things you can do after completing this chapter": "完成本章后能做到的事情",
    "1. Can explain the historical background of Python becoming a standard ML language": "1. 能够解释Python成为ML标准语言的历史背景",
    "2. You can use basic grammar such as variables, data types, operators, and control statements": "2. 能够使用变量、数据类型、运算符和控制语句等基础语法",
    "3. You can compare the time complexity of list, tuple, dict, and set and select appropriately": "3. 能够比较list、tuple、dict和set的时间复杂度并进行适当选择",
    "4. Can implement functions, classes, and sklearn's fit/predict/transform patterns": "4. 能够实现函数、类以及sklearn的fit/predict/transform模式",
    "5. Performance optimization techniques such as NumPy vectorization, profiling, and GIL bypass can be applied": "5. 能够应用NumPy向量化、性能分析和GIL绕过等性能优化技术",
    "6. You can build conda/venv virtual environment and Jupyter Notebook environment": "6. 能够搭建conda/venv虚拟环境和Jupyter Notebook环境",
    "7. You can implement an end-to-end ML pipeline using only pure Python.": "7. 能够仅使用纯Python实现端到端ML流水线。",

    # === SLIDE 4 ===
    "SECTION 1": "第1节",
    "Why Python": "为什么选择Python",
    "History and reasons for the ML standard language": "ML标准语言的历史与原因",

    # === SLIDE 5 ===
    "History of becoming a ML standard language": "成为ML标准语言的历程",
    "Milestones from 1991 to present": "从1991年至今的里程碑",
    "Year": "年份",
    "Milestone": "里程碑",
    "Significance": "意义",
    "Python 0.9 released": "Python 0.9发布",
    "van Rossum's 'batteries included' philosophy": "van Rossum\u7684\u201c\u81ea\u5e26\u7535\u6c60\u201d\u54f2\u5b66",
    "SciPy project start": "SciPy项目启动",
    "Seed of scientific computing ecosystem": "科学计算生态系统的种子",
    "NumPy 1.0 (Oliphant)": "NumPy 1.0（Oliphant）",
    "High-performance ndarray - core infrastructure of ML": "高性能ndarray——ML的核心基础设施",
    "IPython Announcement ||| Survey": "IPython发布 ||| 综述",
    "Overview of the entire Python ML ecosystem": "Python ML生态系统全景概览",
    "scikit-learn 0.1 공개": "scikit-learn 0.1发布",
    "일관된 fit/predict/transform API": "统一的fit/predict/transform API",
    "Jupyter Notebook 분리": "Jupyter Notebook独立",
    "언어 독립적 리터릿 컴퓨팅 플랫폼": "语言无关的文学化计算平台",
    "TensorFlow 공개": "TensorFlow发布",
    "딥러닝 프레임워크 시대 개막": "深度学习框架时代开启",
    "PyTorch 공개": "PyTorch发布",
    "동적 계산 그래프, 연구 친화적": "动态计算图，研究友好",
    "Raschka et al. 서베이": "Raschka等人综述",
    "파이썬 ML 생태계 전체 조망": "Python ML生态系统全景展望",

    # === SLIDE 6 ===
    "3 reasons why Python became the ML standard": "Python成为ML标准的3个原因",
    "1. Glue Language || Rich ecosystem": "1. 胶水语言 || 丰富的生态系统",
    "Supports all stages of ML pipeline": "支持ML流水线的所有阶段",
    "Data collection → preprocessing → modeling → distribution": "数据收集 → 预处理 → 建模 → 部署",
    "3. Low barrier to entry": "3. 低入门门槛",
    "Dynamic typing, concise grammar": "动态类型，简洁语法",
    "Indentation-based block structure": "基于缩进的代码块结构",
    "NumPy, Pandas, scikit-learn": "NumPy、Pandas、scikit-learn",
    "TensorFlow, PyTorch, matplotlib": "TensorFlow、PyTorch、matplotlib",
    "Quick learning even for non-majors": "非专业人士也能快速学习",
    "TIOBE Index 1st place (2024~)": "TIOBE指数第1名（2024~）",
    "3. 낮은 진입 장벽": "3. 低入门门槛",
    "동적 타이핑, 간결한 문법": "动态类型，简洁语法",
    "들여쓰기 기반 블록 구조": "基于缩进的代码块结构",
    "비전공자도 빠르게 학습 가능": "非专业人士也能快速学习",
    "TIOBE 인덱스 1위 (2024~)": "TIOBE指数第1名（2024~）",

    # === SLIDE 7 ===
    "Python vs R vs Julia vs MATLAB": "Python vs R vs Julia vs MATLAB",
    "Comparison of each language's strengths and ML suitability": "各语言优势与ML适用性比较",
    "Criteria": "标准",
    "Python": "Python",
    "R": "R",
    "Julia": "Julia",
    "MATLAB": "MATLAB",
    "Main areas": "主要领域",
    "General-purpose+ML/DL": "通用+ML/DL",
    "Statistical analysis": "统计分析",
    "High-performance numerical value": "高性能数值计算",
    "Engineering simulation": "工程仿真",
    "Performance": "性能",
    "Medium (NumPy supplement)": "中等（NumPy补充）",
    "Slow (Rcpp supplement)": "慢（Rcpp补充）",
    "Fast (C level)": "快速（C级别）",
    "Medium": "中等",
    "DL Framework": "深度学习框架",
    "TF, PyTorch": "TF、PyTorch",
    "Limited || | | Limited | High": "有限 || | | 有限 | 高",
    "Flux.jl": "Flux.jl",
    "Low": "低",
    "Key: No language beats Python for the breadth of its ecosystem, covering the entire ML pipeline in one language.": "关键：在生态系统的广度上，没有任何语言能超越Python，用一种语言覆盖整个ML流水线。",
    "성장 중": "增长中",
    "학교/기업 중심": "以学校/企业为中心",
    "라이선스": "许可证",
    "오픈소스(무료)": "开源（免费）",
    "상용(유료)": "商用（付费）",
    "산업 채택": "行业采用",
    "매우 높음": "非常高",
    "중간": "中等",
    "낮음": "低",
    "핵심: ML 전체 파이프라인을 하나의 언어로 커버하는 생태계의 폭에서 파이썬을 능가하는 언어는 없다": "关键：在生态系统的广度上，没有任何语言能超越Python，用一种语言覆盖整个ML流水线",

    # === SLIDE 8 ===
    "Python design philosophy: The Zen of Python |||": "Python设计哲学：The Zen of Python |||",
    "import this": "import this",
    "# Beautiful is better than ugly.": "# Beautiful is better than ugly.",
    "#   → 가독성 최우선": "#   → 可读性优先",
    "# Explicit is better than implicit.": "# Explicit is better than implicit.",
    "#   → 명시적 코드 선호": "#   → 偏好显式代码",
    "# Simple is better than complex.": "# Simple is better than complex.",
    "#   → 단순한 해법 추구": "#   → 追求简单的解法",
    "# There should be one obvious way to do it.": "# There should be one obvious way to do it.",
    "#   → 일관된 API 설계": "#   → 统一的API设计",
    "scikit-learn에 반영된 철학": "在scikit-learn中体现的哲学",
    "fit() → 학습": "fit() → 训练",
    "predict() → 예측": "predict() → 预测",
    "transform() → 변환": "transform() → 转换",
    "일관된 API = 'one obvious way'": "统一的API = 'one obvious way'",
    "모든 모델이 동일 패턴 따름": "所有模型遵循相同模式",

    # === SLIDE 9 ===
    "SECTION 2": "第2节",
    "Basic grammar": "基础语法",
    "Variables, data types, operators, control statements": "变量、数据类型、运算符、控制语句",

    # === SLIDE 10 ===
    "Variables and Dynamic Typing": "变量与动态类型",
    "Automatically determined based on value without data type declaration": "无需声明数据类型，根据值自动确定",
    "# Variable assignment - no data type declaration required": "# 变量赋值——无需声明数据类型",
    "x = 42          # int": "x = 42          # int",
    "y = 3.14        # float": "y = 3.14        # float",
    "name = 'ML'     # str": "name = 'ML'     # str",
    "is_valid = True  # bool": "is_valid = True  # bool",
    "# Dynamic typing: Reassignment of a different type to the same variable": "# 动态类型：可以将不同类型重新赋值给同一变量",
    "x = 'Now string' # Change from int → str": "x = 'Now string' # 从int → str的类型转换",
    "print(type(x))     # <class 'str'>": "print(type(x))     # <class 'str'>",
    "ML variable naming convention": "ML变量命名规范",
    "data || |": "data || |",
    "X_train / X_test = 분할된 데이터": "X_train / X_test = 分割后的数据",
    "n_samples, n_features = 데이터 차원": "n_samples, n_features = 数据维度",
    "주의: 정적 vs 동적 타이핑": "注意：静态 vs 动态类型",
    "정적(C, Java): 컴파일 시 타입 오류 발견 → 안전": "静态（C、Java）：编译时发现类型错误 → 安全",
    "동적(Python): 런타임 시 타입 오류 발견 → 유연": "动态（Python）：运行时发现类型错误 → 灵活",

    # === SLIDE 11 ===
    "Data types and arithmetic operators": "数据类型与算术运算符",
    "4 basic data types + 7 operators": "4种基本数据类型 + 7种运算符",
    "Data type": "数据类型",
    "Notation": "表示法",
    "Example": "示例",
    "ML context": "ML上下文",
    "Integer": "整数",
    "int": "int",
    "42": "42",
    "Class label, index": "类别标签，索引",
    "Real number": "实数",
    "float": "float",
    "3.14": "3.14",
    "Feature value, weight, loss": "特征值，权重，损失",
    "String": "字符串",
    "str": "str",
    "'hello'": "'hello'",
    "Categorical feature, text": "分类特征，文本",
    "Logical type": "逻辑类型",
    "bool": "bool",
    "True/False": "True/False",
    "Mask, condition Filter": "掩码，条件过滤",
    "Operator |": "运算符 |",
    "의미": "含义",
    "예시": "示例",
    "결과": "结果",
    "+": "+",
    "덧셈": "加法",
    "3 + 2": "3 + 2",
    "5": "5",
    "-": "-",
    "뺄셈": "减法",
    "3 - 2": "3 - 2",
    "1": "1",
    "*": "*",
    "곱셈": "乘法",
    "3 * 2": "3 * 2",
    "6": "6",
    "/": "/",
    "나눗셈": "除法",
    "7 / 2": "7 / 2",
    "3.5 (항상 float)": "3.5（始终为float）",
    "//": "//",
    "몫": "商",
    "7 // 2": "7 // 2",
    "3": "3",
    "%": "%",
    "나머지": "余数",
    "7 % 2": "7 % 2",
    "**": "**",
    "거듭제곱": "幂运算",
    "3 ** 2": "3 ** 2",
    "9": "9",

    # === SLIDE 12 ===
    "Impact of float precision on ML": "float精度对ML的影响",
    "IEEE 754 Floating Point Limits and Dealing with them": "IEEE 754浮点数的局限性及应对方法",
    "# IEEE 754 Floating Point Limitations": "# IEEE 754浮点数的局限性",
    "print(0.1 + 0.2)         # 0.30000000000000004": "print(0.1 + 0.2)         # 0.30000000000000004",
    "print(0.1 + 0.2 == 0.3)  # False !!": "print(0.1 + 0.2 == 0.3)  # False !!",
    "# How to Compare Correctly": "# 正确的比较方法",
    "import math": "import math",
    "print(math.isclose(0.1 + 0.2, 0.3))  # True": "print(math.isclose(0.1 + 0.2, 0.3))  # True",
    "Why Precision is Important in ML": "为什么精度在ML中很重要",
    "float32 Precision ≈ 10⁻⁷": "float32 精度 ≈ 10⁻⁷",
    "float64 Precision ≈ 10⁻¹⁶": "float64 精度 ≈ 10⁻¹⁶",
    "Gradient descent: Vanishing gradient in float32 when η=10⁻⁶": "梯度下降：float32中当η=10⁻⁶时梯度消失",
    "Loss function: If p→0 in log(p), -∞ divergence": "损失函数：log(p)中若p→0，则发散至-∞",
    "→ Requires np.clip(p, 1e-15, 1)": "→ 需要np.clip(p, 1e-15, 1)",
    "Mixed precision: GPU optimization with float16 + float32": "混合精度：使用float16 + float32进行GPU优化",
    "Formula: float32 precision ≈ 10⁻⁷, float64 precision ≈ 10⁻¹⁶": "公式：float32精度 ≈ 10⁻⁷，float64精度 ≈ 10⁻¹⁶",

    # === SLIDE 13 ===
    "Conditional statements and loops": "条件语句与循环",
    "if-elif-else, for, while, enumerate": "if-elif-else、for、while、enumerate",
    "# Conditional statement: if-elif-else": "# 条件语句：if-elif-else",
    "score = 85": "score = 85",
    "if score >= 90:": "if score >= 90:",
    "    grade = 'A'": "    grade = 'A'",
    "elif score >= 80:": "elif score >= 80:",
    "    grade = 'B'": "    grade = 'B'",
    "else:": "else:",
    "    grade = 'C'": "    grade = 'C'",
    "# for loop": "# for循环",
    "for i in range(5):": "for i in range(5):",
    "    print(i, end=' ')  # 0 1 2 3 4": "    print(i, end=' ')  # 0 1 2 3 4",
    "# enumerate: Index + value simultaneously": "# enumerate：同时获取索引+值",
    "fruits = ['apple', 'banana', 'cherry']": "fruits = ['apple', 'banana', 'cherry']",
    "for idx, fruit in enumerate(fruits):": "for idx, fruit in enumerate(fruits):",
    "    print(f'{idx}: {fruit}')": "    print(f'{idx}: {fruit}')",
    "# f-string: Frequently used output patterns in ML": "# f-string：ML中常用的输出模式",
    "epoch, loss, acc = 10, 0.0342, 0.9821": "epoch, loss, acc = 10, 0.0342, 0.9821",
    "print(f'Epoch {epoch:3d} | Loss: {loss:.4f}'": "print(f'Epoch {epoch:3d} | Loss: {loss:.4f}'",
    "      f' | Acc: {acc:.4f}')": "      f' | Acc: {acc:.4f}')",
    "# Epoch  10 | Loss: 0.0342 | Acc: 0.9821": "# Epoch  10 | Loss: 0.0342 | Acc: 0.9821",
    "f-string formatting": "f-string格式化",
    ":3d = 3-digit integer, :.4f = decimal point 4 digits": ":3d = 3位整数，:.4f = 小数点后4位",
    ":.2% = percentage display (0.95 → 95.00%)": ":.2% = 百分比显示（0.95 → 95.00%）",

    # === SLIDE 14 ===
    "List Comprehension": "列表推导式",
    "Python's unique syntax that reduces the for statement to one line": "Python独特的语法，将for循环缩减为一行",
    "# Basic: [expression for variable in iterable]": "# 基础：[表达式 for 变量 in 可迭代对象]",
    "squares = [x ** 2 for x in range(1, 6)]       # [1, 4, 9, 16, 25]": "squares = [x ** 2 for x in range(1, 6)]       # [1, 4, 9, 16, 25]",
    "# Condition included: [Expression for variable in iterable if condition]": "# 含条件：[表达式 for 变量 in 可迭代对象 if 条件]",
    "evens = [x for x in range(1, 21) if x % 2 == 0]  # [2, 4, ..., 20]": "evens = [x for x in range(1, 21) if x % 2 == 0]  # [2, 4, ..., 20]",
    "# If-else included: [Expression1 if condition else Expression2 for variable in iterable]": "# 含if-else：[表达式1 if 条件 else 表达式2 for 变量 in 可迭代对象]",
    "labels = [1 if x > 0 else 0 for x in [-1, 3, -2, 5, 0]]  # [0, 1, 0, 1, 0]": "labels = [1 if x > 0 else 0 for x in [-1, 3, -2, 5, 0]]  # [0, 1, 0, 1, 0]",
    "# ML usage example": "# ML使用示例",
    "# Data preprocessing: Missing values Remove": "# 数据预处理：缺失值删除",
    "cleaned = [x for x in raw_data if x is not None]": "cleaned = [x for x in raw_data if x is not None]",
    "# Label Encoding": "# 标签编码",
    "encoded = [1 if label == 'positive' else 0 for label in labels]": "encoded = [1 if label == 'positive' else 0 for label in labels]",
    "ML Core Uses: Very often used in data preprocessing, feature extraction, label encoding": "ML核心用途：在数据预处理、特征提取、标签编码中使用非常频繁",

    # === SLIDE 15 ===
    "SECTION 3": "第3节",
    "Advanced Data Structure": "数据结构进阶",
    "Characteristics and time complexity of list, tuple, dict, and set": "list、tuple、dict和set的特性与时间复杂度",

    # === SLIDE 16 ===
    "Comparison of four basic data structures ||| O(1). Overwhelming compared to list's O(n) in large data": "四种基本数据结构的比较 ||| O(1)。在大数据量下远超list的O(n)",
    "특성과 용도": "特性与用途",
    "자료구조": "数据结构",
    "기호": "符号",
    "변경 가능": "可变性",
    "순서 보장": "有序性",
    "중복 허용": "允许重复",
    "해시 기반": "基于哈希",
    "리스트 (list)": "列表（list）",
    "[ ]": "[ ]",
    "O (mutable)": "O（可变）",
    "O": "O",
    "X": "X",
    "튜플 (tuple)": "元组（tuple）",
    "( )": "( )",
    "X (immutable)": "X（不可变）",
    "딕셔너리 (dict)": "字典（dict）",
    "{ }": "{ }",
    "O (3.7+)": "O（3.7+）",
    "키 X": "键 X",
    "세트 (set)": "集合（set）",
    "핵심: dict와 set은 해시 테이블 기반이므로 탐색이 O(1). 대용량 데이터에서 list의 O(n) 대비 압도적": "关键：dict和set基于哈希表，查找为O(1)。在大数据量下远超list的O(n)",

    # === SLIDE 17 ===
    "Time complexity comparison (Big-O) ||": "时间复杂度比较（Big-O）||",
    "연산별 성능 특성": "各操作的性能特性",
    "연산": "操作",
    "list": "list",
    "tuple": "tuple",
    "dict": "dict",
    "set": "set",
    "인덱스 접근 [i]": "索引访问 [i]",
    "O(1)": "O(1)",
    "N/A": "N/A",
    "탐색 (in)": "查找（in）",
    "O(n)": "O(n)",
    "끝 삽입": "末尾插入",
    "O(1)*": "O(1)*",
    "앞 삽입": "前端插入",
    "끝 삭제": "末尾删除",
    "앞 삭제": "前端删除",
    "*O(1) 분할상환(amortized): 리스트 용량 초과 시 내부적으로 배열을 2배 확장": "*O(1) 均摊时间(amortized)：当列表容量超出时，内部数组扩大为2倍",

    # === SLIDE 18 ===
    "list details": "list详解",
    "variable, guaranteed order, indexing/slicing": "可变、有序、索引/切片",
    "# Creation and indexing": "# 创建与索引",
    "data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]": "data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]",
    "print(data[0]) # 1 (first)": "print(data[0]) # 1（第一个）",
    "print(data[-1]) # 10 (last)": "print(data[-1]) # 10（最后一个）",
    "# slicing: [start:end:interval]": "# 切片：[起始:结束:步长]",
    "print(data[2:5])   # [3, 4, 5]": "print(data[2:5])   # [3, 4, 5]",
    "print(data[::2])   # [1, 3, 5, 7, 9]": "print(data[::2])   # [1, 3, 5, 7, 9]",
    "print(data[::-1]) # [10, 9, ..., 1] Reverse order": "print(data[::-1]) # [10, 9, ..., 1] 逆序",
    "# Main method": "# 主要方法",
    "data.append(100) # Append to the end O(1)": "data.append(100) # 末尾追加 O(1)",
    "data.insert(0, 99) # Insert before O(n)": "data.insert(0, 99) # 前端插入 O(n)",
    "data.remove(100) # Delete by value O(n)": "data.remove(100) # 按值删除 O(n)",
    "removed = data.pop() # Remove from the end O(1)": "removed = data.pop() # 末尾删除 O(1)",
    "Slicing rule": "切片规则",
    "[start:end] → end index Not included": "[start:end] → 不包含end索引",
    "[::interval] → Skip by interval": "[::步长] → 按步长跳跃",
    "[::-1] → Reverse order (reverse entire order)": "[::-1] → 逆序（反转整个顺序）",
    "Often used in ML:": "在ML中常用：",
    "  X_train = data[:split]": "  X_train = data[:split]",
    "  X_test = data[split:]": "  X_test = data[split:]",
    "Performance caution": "性能注意事项",
    "append → O(1), insert(0) → O(n)": "append → O(1)，insert(0) → O(n)",
    "Use collections.deque if front insertion is frequent.": "如果频繁进行前端插入，使用collections.deque。",

    # === SLIDE 19 ===
    "Dictionary (dict) & set (set)": "字典（dict）与集合（set）",
    "O(1) search based on hash table": "基于哈希表的O(1)查找",
    "# Dictionary: {key: value}": "# 字典：{键: 值}",
    "params = {": "params = {",
    "    'n_estimators': 100,": "    'n_estimators': 100,",
    "    'max_depth': 5,": "    'max_depth': 5,",
    "    'learning_rate': 0.1,": "    'learning_rate': 0.1,",
    "}": "}",
    "# model = dict (pass **kwargs)": "# model = dict（传递**kwargs）",
    "Mapping category labels → dict (string → integer encoding)": "映射类别标签 → dict（字符串 → 整数编码）",
    "train_feats = {'age', 'income', 'score'}": "train_feats = {'age', 'income', 'score'}",
    "test_feats = {'age', 'income', 'name'}": "test_feats = {'age', 'income', 'name'}",
    "missing = train_feats - test_feats  # {'score'}": "missing = train_feats - test_feats  # {'score'}",
    "Extract unique categories → set (remove duplicates, O(1) search)": "提取唯一类别 → set（去重，O(1)查找）",
    "Model settings (immutable) → tuple (avoid accidental changes)": "模型设置（不可变）→ tuple（防止意外修改）",
    "Fast membership check → set / dict": "快速成员检查 → set / dict",
    "범주 레이블 매핑 → dict (문자열→정수 인코딩)": "类别标签映射 → dict（字符串→整数编码）",
    "고유 카테고리 추출 → set (중복 제거, O(1) 탐색)": "提取唯一类别 → set（去重，O(1)查找）",
    "모델 설정 (불변) → tuple (실수 변경 방지)": "模型设置（不可变）→ tuple（防止意外修改）",
    "빠른 멤버십 검사 → set / dict": "快速成员检查 → set / dict",

    # === SLIDE 20 ===
    "SECTION 4": "第4节",
    "Functions and classes": "函数与类",
    "def, lambda, classes, sklearn patterns": "def、lambda、类、sklearn模式",

    # === SLIDE 21 ===
    "Function Definitions and Advanced Features": "函数定义与高级特性",
    "Default, *args, **kwargs, multiple returns": "默认参数、*args、**kwargs、多返回值",
    "# Default Parameters": "# 默认参数",
    "def train(data, epochs=10, lr=0.01):": "def train(data, epochs=10, lr=0.01):",
    "print(f'train: {epochs} epochs, learning rate={lr}')": "print(f'train: {epochs} epochs, learning rate={lr}')",
    "train(data) # Use defaults": "train(data) # 使用默认值",
    "train(data, epochs=50) # Only change epochs": "train(data, epochs=50) # 仅更改epochs",
    "# *args: Variable positional arguments (tuple)": "# *args：可变位置参数（元组）",
    "def add_all(*args):": "def add_all(*args):",
    "    return sum(args)": "    return sum(args)",
    "# **kwargs: Variable keyword arguments (dictionary)": "# **kwargs：可变关键字参数（字典）",
    "def create_model(**kwargs):": "def create_model(**kwargs):",
    "    for key, val in kwargs.items():": "    for key, val in kwargs.items():",
    "        print(f'  {key} = {val}')": "        print(f'  {key} = {val}')",
    "Multiple value returns (tuple)": "多值返回（元组）",
    "def calc_stats(numbers):": "def calc_stats(numbers):",
    "    total = sum(numbers)": "    total = sum(numbers)",
    "    avg = total / len(numbers)": "    avg = total / len(numbers)",
    "    return total, avg, min(numbers)": "    return total, avg, min(numbers)",
    "total, avg, min_v = calc_stats([85,90,78])": "total, avg, min_v = calc_stats([85,90,78])",
    "Using **kwargs in ML": "在ML中使用**kwargs",
    "params = {'n_estimators':100, 'max_depth':5}": "params = {'n_estimators':100, 'max_depth':5}",
    "model = RandomForestClassifier(**params)": "model = RandomForestClassifier(**params)",

    # === SLIDE 22 ===
    "lambda functions and higher-order functions": "lambda函数与高阶函数",
    "Used in sorted, map, filter": "在sorted、map、filter中使用",
    "# lambda: Anonymous function (one-line function)": "# lambda：匿名函数（单行函数）",
    "square = lambda x: x ** 2": "square = lambda x: x ** 2",
    "print(square(5))  # 25": "print(square(5))  # 25",
    "# sorted() + lambda: Sort feature importance": "# sorted() + lambda：对特征重要性排序",
    "feature_importance = [('age', 0.35), ('income', 0.52), ('score', 0.13)]": "feature_importance = [('age', 0.35), ('income', 0.52), ('score', 0.13)]",
    "sorted_features = sorted(feature_importance, key=lambda x: x[1], reverse=True)": "sorted_features = sorted(feature_importance, key=lambda x: x[1], reverse=True)",
    "# [('income', 0.52), ('age', 0.35), ('score', 0.13)]": "# [('income', 0.52), ('age', 0.35), ('score', 0.13)]",
    "# map(): Data conversion |  filter(): data filtering": "# map()：数据转换 |  filter()：数据过滤",
    "data = [1, -2, 3, -4, 5]": "data = [1, -2, 3, -4, 5]",
    "positives = list(filter(lambda x: x > 0, data))   # [1, 3, 5]": "positives = list(filter(lambda x: x > 0, data))   # [1, 3, 5]",
    "squared = list(map(lambda x: x ** 2, data))        # [1, 4, 9, 16, 25]": "squared = list(map(lambda x: x ** 2, data))        # [1, 4, 9, 16, 25]",

    # === SLIDE 23 ===
    "sklearn's fit/predict/transform patterns": "sklearn的fit/predict/transform模式",
    "Estimator API - consistent interface for all models": "Estimator API——所有模型的统一接口",
    "class SimpleScaler:": "class SimpleScaler:",
    "    def __init__(self, feature_range=(0, 1)):": "    def __init__(self, feature_range=(0, 1)):",
    "        self.feature_range = feature_range": "        self.feature_range = feature_range",
    "        self.min_ = None": "        self.min_ = None",
    "        self.max_ = None": "        self.max_ = None",
    "def fit(self, X): # Learn statistics from training data": "def fit(self, X): # 从训练数据中学习统计量",
    "        self.min_ = min(X)": "        self.min_ = min(X)",
    "        self.max_ = max(X)": "        self.max_ = max(X)",
    "        return self": "        return self",
    "def transform(self, (Convenience)": "def transform(self,（便捷方式）",
    "        range_ = self.max_ - self.min_": "        range_ = self.max_ - self.min_",
    "        lo, hi = self.feature_range": "        lo, hi = self.feature_range",
    "        return [(x-self.min_)/range_*(hi-lo)+lo": "        return [(x-self.min_)/range_*(hi-lo)+lo",
    "                for x in X]": "                for x in X]",
    "Important: fit() must only be used on training data!": "重要：fit()只能在训练数据上使用！",
    "Calling fit() on test data = data leakage": "在测试数据上调用fit() = 数据泄露",
    "호출 시점": "调用时机",
    "fit(X)": "fit(X)",
    "학습 데이터에서 파라미터 학습": "从训练数据中学习参数",
    "학습 시": "训练时",
    "predict(X)": "predict(X)",
    "학습된 모델로 예측 수행": "使用训练好的模型进行预测",
    "추론 시": "推理时",
    "transform(X)": "transform(X)",
    "학습된 파라미터로 데이터 변환": "使用学习到的参数进行数据转换",
    "학습/추론 시": "训练/推理时",
    "fit_transform(X)": "fit_transform(X)",
    "fit + transform 한 번에": "一次完成fit + transform",
    "학습 시 (편의)": "训练时（便捷方式）",
    "중요: fit()은 반드시 학습 데이터에서만!": "重要：fit()只能在训练数据上使用！",
    "테스트 데이터에 fit() 호출 = 데이터 누출(data leakage)": "在测试数据上调用fit() = 数据泄露（data leakage）",

    # === SLIDE 24 ===
    "Class inheritance and polymorphism |||  All support fit() → predict() → score()": "类继承与多态 |||  全部支持fit() → predict() → score()",
    "BaseModel → 구체적 모델 구현 패턴": "BaseModel → 具体模型实现模式",
    "# 기본 모델 클래스 (추상 기반)": "# 基础模型类（抽象基类）",
    "class BaseModel:": "class BaseModel:",
    "    def fit(self, X, y):": "    def fit(self, X, y):",
    "        raise NotImplementedError": "        raise NotImplementedError",
    "    def predict(self, X):": "    def predict(self, X):",
    "    def score(self, X, y):": "    def score(self, X, y):",
    "        preds = self.predict(X)": "        preds = self.predict(X)",
    "        correct = sum(1 for p,t": "        correct = sum(1 for p,t",
    "                      in zip(preds,y) if p==t)": "                      in zip(preds,y) if p==t)",
    "        return correct / len(y)": "        return correct / len(y)",
    "# 구체적 모델 구현": "# 具体模型实现",
    "class MajorityClassifier(BaseModel):": "class MajorityClassifier(BaseModel):",
    "    def fit(self, X, y):": "    def fit(self, X, y):",
    "        from collections import Counter": "        from collections import Counter",
    "        self.majority_ = Counter(y)": "        self.majority_ = Counter(y)",
    "            .most_common(1)[0][0]": "            .most_common(1)[0][0]",
    "        return self": "        return self",
    "다형성 (Polymorphism)의 장점": "多态（Polymorphism）的优势",
    "동일한 인터페이스로 다른 모델 사용 가능": "可以使用相同的接口调用不同的模型",
    "model = MajorityClassifier()": "model = MajorityClassifier()",
    "model.fit(None, [0,0,1,0,1,0])": "model.fit(None, [0,0,1,0,1,0])",
    "model.predict([1,2,3])  # [0, 0, 0]": "model.predict([1,2,3])  # [0, 0, 0]",
    "model.score(None, [0,0,1])  # 0.667": "model.score(None, [0,0,1])  # 0.667",
    "sklearn의 모든 모델이 이 패턴:": "sklearn的所有模型都遵循此模式：",
    "  LogisticRegression, SVC, RandomForest...": "  LogisticRegression、SVC、RandomForest...",
    "  모두 fit() → predict() → score() 지원": "  全部支持fit() → predict() → score()",

    # === SLIDE 25 ===
    "SECTION 5": "第5节",
    "Performance optimization": "性能优化",
    "Profiling, vectorization, GIL, memory management": "性能分析、向量化、GIL、内存管理",

    # === SLIDE 26 ===
    "Profiling: Finding bottlenecks": "性能分析：发现瓶颈",
    "Don't optimize if you don't measure it": "不测量就不要优化",
    "import time, cProfile": "import time, cProfile",
    "# Method 1: time.perf_counter()": "# 方法1：time.perf_counter()",
    "start = time.perf_counter()": "start = time.perf_counter()",
    "result = sum(x**2 for x in range(1_000_000))": "result = sum(x**2 for x in range(1_000_000))",
    "elapsed = time.perf_counter() - start": "elapsed = time.perf_counter() - start",
    "print(f'Running time: {elapsed:.4f} seconds')": "print(f'运行时间：{elapsed:.4f}秒')",
    "# Method 2: cProfile (details per function)": "# 方法2：cProfile（按函数的详细信息）",
    "def my_function():": "def my_function():",
    "    data = [x**2 for x in range(100_000)]": "    data = [x**2 for x in range(100_000)]",
    "    return sorted(data, reverse=True)": "    return sorted(data, reverse=True)",
    "cProfile.run('my_function()')": "cProfile.run('my_function()')",
    "# Method 3: Jupyter %timeit": "# 方法3：Jupyter %timeit",
    "# %timeit sum(range(1000))": "# %timeit sum(range(1000))",
    "Profiling Step 3": "性能分析三步骤",
    "Step 1: time.perf_counter()": "步骤1：time.perf_counter()",
    "→ Simple section measurement": "→ 简单的区间测量",
    "→ Identify bottlenecks as quickly as possible": "→ 尽快识别瓶颈",
    "Step 2: cProfile": "步骤2：cProfile",
    "→ Number of calls per function, cumulative time": "→ 每个函数的调用次数，累计时间",
    "→ In-depth analysis of which functions are slow": "→ 深入分析哪些函数较慢",
    "Step 3: line_profiler": "步骤3：line_profiler",
    "→ Line-by-line execution time analysis": "→ 逐行执行时间分析",
    "→ Identify the exact bottleneck point": "→ 精确定位瓶颈点",

    # === SLIDE 27 ===
    "Vectorization: The power of NumPy": "向量化：NumPy的力量",
    "Dozens to hundreds of times faster than pure Python loops": "比纯Python循环快数十到数百倍",
    "import numpy as np": "import numpy as np",
    "n = 1_000_000": "n = 1_000_000",
    "data_list = list(range(n))": "data_list = list(range(n))",
    "data_array = np.arange(n)": "data_array = np.arange(n)",
    "# Pure Python loop: ~0.15 seconds": "# 纯Python循环：~0.15秒",
    "result_loop = [x ** 2 for x in data_list]": "result_loop = [x ** 2 for x in data_list]",
    "# NumPy vectorization: ~0.002 seconds (about 75 times faster!)": "# NumPy向量化：~0.002秒（快约75倍！）",
    "result_numpy = data_array ** 2": "result_numpy = data_array ** 2",
    "3 reasons why vectorization is fast": "向量化快速的3个原因",
    "1. C-level inner loop: eliminate interpreter overhead": "1. C级内部循环：消除解释器开销",
    "2. Continuous memory access: Maximizing CPU cache efficiency": "2. 连续内存访问：最大化CPU缓存效率",
    "3. SIMD Instructions: Hardware-Level Parallelism": "3. SIMD指令：硬件级并行",
    "Speed \u200b\u200bComparison": "速度比较",
    "for loop     ~150ms": "for循环     ~150ms",
    "list comp.   ~100ms": "列表推导   ~100ms",
    "map()        ~120ms": "map()        ~120ms",
    "NumPy         ~2ms": "NumPy         ~2ms",
    "NumPy is ~75x faster than for loops": "NumPy比for循环快约75倍",
    "Key Lessons:": "关键经验：",
    "Be sure to use NumPy for numerical calculations!": "数值计算务必使用NumPy！",
    "In pure Python, comprehension is optimal.": "在纯Python中，推导式是最优的。",

    # === SLIDE 28 ===
    "GIL (Global Interpreter Lock)": "GIL（全局解释器锁）",
    "CPython's global locking and its response in ML": "CPython的全局锁及其在ML中的应对策略",
    "What is GIL?": "什么是GIL？",
    "CPython's global locking mechanism": "CPython的全局锁机制",
    "Only one thread executes Python bytecode at a time": "同一时间只有一个线程执行Python字节码",
    "CPU bound: Performance cannot be improved by multithreading": "CPU密集型：多线程无法提升性能",
    "I/O bound: Multithreading has an effect (GIL is turned off)": "I/O密集型：多线程有效（GIL被释放）",
    "Strategy": "策略",
    "Tools": "工具",
    "Application Situation": "应用场景",
    "Multiprocessing": "多进程",
    "multiprocessing, joblib": "multiprocessing、joblib",
    "CPU parallel learning": "CPU并行学习",
    "NumPy internal": "NumPy内部",
    "BLAS/MKL": "BLAS/MKL",
    "Matrix computation automatically parallel": "矩阵计算自动并行",
    "External library": "外部库",
    "TensorFlow, PyTorch": "TensorFlow、PyTorch",
    "GPU computation (GIL independent)": "GPU计算（与GIL无关）",
    "Asynchronous I/O": "异步I/O",
    "asyncio": "asyncio",
    "Data loading pipeline": "数据加载流水线",
    "# scikit-learn's n_jobs parameter": "# scikit-learn的n_jobs参数",
    "# Multiprocessing used internally": "# 内部使用多进程",
    "from sklearn.ensemble import RandomForestClassifier": "from sklearn.ensemble import RandomForestClassifier",
    "model = RandomForestClassifier(": "model = RandomForestClassifier(",
    "n_estimators=100, n_jobs=-1 # All cores": "n_estimators=100, n_jobs=-1 # 所有核心",
    ")": ")",

    # === SLIDE 29 ===
    "Memory Management ||| Efficient": "内存管理 ||| 高效",
    "dict: ~300+ KB → Hash table overhead": "dict：~300+ KB → 哈希表开销",
    "import sys": "import sys",
    "set: ~500+ KB → Hash table overhead": "set：~500+ KB → 哈希表开销",
    "list_mem  = sys.getsizeof(list(range(10000)))": "list_mem  = sys.getsizeof(list(range(10000)))",
    "tuple_mem = sys.getsizeof(tuple(range(10000)))": "tuple_mem = sys.getsizeof(tuple(range(10000)))",
    "dict_mem  = sys.getsizeof({i:i for i in range(10000)})": "dict_mem  = sys.getsizeof({i:i for i in range(10000)})",
    "Large data processing strategy:": "大数据处理策略：",
    "gen = (x ** 2 for x in range(1_000_000))": "gen = (x ** 2 for x in range(1_000_000))",
    "print(sys.getsizeof(gen))  # ~200 bytes!": "print(sys.getsizeof(gen))  # ~200字节！",
    "1. Generator batch loading (yield)": "1. 生成器批量加载（yield）",
    "2. np.memmap (disk mapping array)": "2. np.memmap（磁盘映射数组）",
    "4. float64 → float32 downcasting": "4. float64 → float32降精度",
    "tuple: ~80 KB → immutable, 메모리 효율적": "tuple：~80 KB → 不可变，内存高效",
    "dict: ~300+ KB → 해시 테이블 오버헤드": "dict：~300+ KB → 哈希表开销",
    "set: ~500+ KB → 해시 테이블 오버헤드": "set：~500+ KB → 哈希表开销",
    "대용량 데이터 처리 전략:": "大数据处理策略：",
    "  1. 제너레이터 배치 로딩 (yield)": "  1. 生成器批量加载（yield）",
    "  2. np.memmap (디스크 매핑 배열)": "  2. np.memmap（磁盘映射数组）",
    "  3. pd.read_csv(chunksize=1000)": "  3. pd.read_csv(chunksize=1000)",
    "  4. float64 → float32 다운캐스팅": "  4. float64 → float32降精度",

    # === SLIDE 30 ===
    "SECTION 6": "第6节",
    "Development environment": "开发环境",
    "Virtual environment, Jupyter, IDE, debugging": "虚拟环境、Jupyter、IDE、调试",

    # === SLIDE 31 ===
    "Virtual environment: conda vs venv": "虚拟环境：conda vs venv",
    "Build independent environment for each project": "为每个项目构建独立环境",
    "# venv (built-in Python)": "# venv（Python内置）",
    "python -m venv ml_env": "python -m venv ml_env",
    "source ml_env/bin/activate     # Linux/Mac": "source ml_env/bin/activate     # Linux/Mac",
    "ml_env\\Scripts\\activate      # Windows": "ml_env\\Scripts\\activate      # Windows",
    "pip install numpy pandas scikit-learn": "pip install numpy pandas scikit-learn",
    "# conda (Anaconda/Miniconda)": "# conda（Anaconda/Miniconda）",
    "conda create -n ml_env python=3.11": "conda create -n ml_env python=3.11",
    "conda activate ml_env": "conda activate ml_env",
    "conda install numpy pandas scikit-learn": "conda install numpy pandas scikit-learn",
    "Standard": "标准",
    "venv + pip": "venv + pip",
    "conda": "conda",
    "Package source": "包来源",
    "PyPI": "PyPI",
    "Anaconda + PyPI": "Anaconda + PyPI",
    "Binary management": "二进制管理",
    "Limited": "有限",
    "Excellent (C dependency automatic)": "优秀（C依赖自动处理）",
    "GPU settings": "GPU设置",
    "Manual": "手动",
    "Simple (cudatoolkit)": "简单（cudatoolkit）",
    "Recommended": "推荐",
    "Lightweight Project": "轻量级项目",
    "ML/DL Project": "ML/DL项目",

    # === SLIDE 32 ===
    "Jupyter Notebook vs IDE": "Jupyter Notebook vs IDE",
    "Exploratory analysis vs production code": "探索性分析 vs 生产代码",
    "Jupyter Notebook": "Jupyter Notebook",
    "Strengths: Cell-by-cell execution, inline visualization, markdown": "优势：逐单元执行、内联可视化、markdown",
    "Suitable for: EDA, prototyping, lectures/presentations": "适用于：EDA、原型开发、讲座/演示",
    "Magic: %timeit, %matplotlib inline": "魔术命令：%timeit、%matplotlib inline",
    "Limitations: .ipynb JSON format → Git diff inconvenient": "局限性：.ipynb JSON格式 → Git diff不便",
    "IDE (VS Code, PyCharm)": "IDE（VS Code、PyCharm）",
    "Strengths: Debugging, refactoring, autocompletion, Git integration": "优势：调试、重构、自动补全、Git集成",
    "Suitable for: Production code, packages Development ||| == len(y), 'X and y have different lengths!'": "适用于：生产代码、包开发 ||| == len(y), 'X和y长度不同！'",
    ".py 파일 → Git 친화적": ".py文件 → Git友好",
    "VS Code + Jupyter 확장 = 최고 조합": "VS Code + Jupyter扩展 = 最佳组合",
    "실무 워크플로우 & 디버깅 기법": "实战工作流程 & 调试技巧",
    "Jupyter에서 프로토타이핑 → .py 모듈로 리팩토링 → IDE에서 테스트/배포": "在Jupyter中原型开发 → 重构为.py模块 → 在IDE中测试/部署",
    "디버깅 4단계: print() → assert → pdb.set_trace() → IDE 디버거": "调试4步骤：print() → assert → pdb.set_trace() → IDE调试器",
    "방어적 프로그래밍: assert len(X) == len(y), 'X와 y의 길이가 다릅니다!'": "防御性编程：assert len(X) == len(y), 'X和y长度不同！'",

    # === SLIDE 33 ===
    "SECTION 7": "第7节",
    "Paper Review": "论文综述",
    "Analysis of 5 key papers": "5篇重要论文分析",

    # === SLIDE 34 ===
    "Review of key papers (1/2)": "重要论文综述（1/2）",
    "Papers that laid the foundation of the Python ecosystem": "奠定Python生态系统基础的论文",
    "Van Rossum (2007) - Python Programming Language": "Van Rossum（2007）- Python编程语言",
    "USENIX Annual Technical Conference (Invited Talk)": "USENIX年度技术会议（特邀报告）",
    "Design philosophy explained by the creator of Python": "Python创始人阐述的设计哲学",
    "Dynamic typing, GIL, scalability architecture": "动态类型、GIL、可扩展性架构",
    "Millman & Aivazis (2011) - Python for Scientists": "Millman & Aivazis（2011）- 面向科学家的Python",
    "Computing in Science & Engineering, 13(2)": "Computing in Science & Engineering, 13(2)",
    "SciPy stack is the foundation of scientific computing": "SciPy技术栈是科学计算的基础",
    "Importance of software engineering practices": "软件工程实践的重要性",
    "Oliphant (2007) - Python for Scientific Computing": "Oliphant（2007）- 面向科学计算的Python",
    "Technical foundation explained by the creator of NumPy": "NumPy创始人阐述的技术基础",
    "ndarray: contiguous memory + stride-based layout": "ndarray：连续内存 + 基于步幅的布局",
    "Utilization of BLAS/LAPACK, f2py/Cython optimization": "利用BLAS/LAPACK，f2py/Cython优化",
    "ML Core: ndarray is the infrastructure for all ML algorithms": "ML核心：ndarray是所有ML算法的基础设施",
    "Perez & Granger (2007) - IPython": "Perez & Granger（2007）- IPython",
    "Predecessor of Jupyter Notebook (kernel-frontend separation)": "Jupyter Notebook的前身（内核-前端分离）",
    "Interactive computing: Think→Coding→Execute→Confirm": "交互式计算：思考→编码→执行→确认",
    "Magic commands: %timeit, %debug, %matplotlib": "魔术命令：%timeit、%debug、%matplotlib",
    "Literet computing: Integration of code+results+explanation": "文学化计算：代码+结果+解释的整合",

    # === SLIDE 35 ===
    "Recommended paper: Raschka et al. (2020)": "推荐论文：Raschka等人（2020）",
    "Machine Learning in Python - Ecosystem Survey": "Python机器学习——生态系统综述",
    "Raschka et al. (2020) - ML in Python": "Raschka等人（2020）- Python中的ML",
    "Information, Vol. 11, No. 4, Article 193": "Information, Vol. 11, No. 4, Article 193",
    "Historical Development:": "历史发展：",
    "  NumPy(2006) → scikit-learn(2010)": "  NumPy(2006) → scikit-learn(2010)",
    "  → TensorFlow(2015) → PyTorch(2016)": "  → TensorFlow(2015) → PyTorch(2016)",
    "Framework Comparison:": "框架比较：",
    "scikit-learn: consistent API": "scikit-learn：统一的API",
    "TensorFlow: Distributed Learning": "TensorFlow：分布式学习",
    "PyTorch: Dynamic Graph, Research Friendly": "PyTorch：动态图，研究友好",
    "Latest Trends:": "最新趋势：",
    "  AutoML, Interpretable ML (SHAP/LIME)": "  AutoML、可解释ML（SHAP/LIME）",
    "  MLOps (MLflow/Kubeflow)": "  MLOps（MLflow/Kubeflow）",
    "Connection to this subject": "与本课程的联系",
    "This survey paper provides an understanding of the entire subject in the context of": "这篇综述论文在以下背景下提供了对整个课程的理解",
    "Python ecosystem": "Python生态系统",
    "Data processing tool evolution:": "数据处理工具演进：",
    "Pandas → Dask (distributed) → RAPIDS (GPU)": "Pandas → Dask（分布式）→ RAPIDS（GPU）",
    "Algorithm lineage to be covered:": "将涵盖的算法脉络：",
    "Linear regression, logistic regression": "线性回归、逻辑回归",
    "Decision Tree, Random Forest": "决策树、随机森林",
    "  XGBoost, LightGBM": "  XGBoost、LightGBM",
    "  KMeans, PCA": "  KMeans、PCA",
    "Ecosystem Task:": "生态系统课题：",
    "GIL, production performance, library compatibility": "GIL、生产性能、库兼容性",

    # === SLIDE 36 ===
    "SECTION 8": "第8节",
    "Hands-on: Python Profiling": "实践：Python性能分析",
    "for loop vs comprehension vs map vs NumPy performance comparison": "for循环 vs 推导式 vs map vs NumPy性能比较",

    # === SLIDE 37 ===
    "Practice Code: Performance Measurement Utility": "实践代码：性能测量工具",
    "01_python_profiling.py": "01_python_profiling.py",
    "import time, numpy as np, matplotlib.pyplot as plt": "import time, numpy as np, matplotlib.pyplot as plt",
    "def Time Measurement(function, *args, number of iterations=5):": "def 时间测量(函数, *args, 重复次数=5):",
    '"""Measure the execution time of a function (average after multiple executions)"""': '"""测量函数的执行时间（多次执行后取平均）"""',
    "Hours = []": "时间列表 = []",
    "for _ in range(number of repetitions):": "for _ in range(重复次数):",
    "start = time.perf_counter()": "start = time.perf_counter()",
    "function(*args)": "函数(*args)",
    "end = time.perf_counter()": "end = time.perf_counter()",
    "hours.append(end - start)": "时间列表.append(end - start)",
    "return np.mean(times)": "return np.mean(times)",
    "# Compare the square operation in 4 ways (data size: 1,000,000)": "# 用4种方式比较平方运算（数据量：1,000,000）",
    "def for loop_square(data): result = []; [result.append(x**2) for x in data]; return result": "def for循环_平方(data): result = []; [result.append(x**2) for x in data]; return result",
    "def comprehension_squared(data): return [x**2 for x in data]": "def 推导式_平方(data): return [x**2 for x in data]",
    "def map_squared(data): return list(map(lambda x: x**2, data))": "def map_平方(data): return list(map(lambda x: x**2, data))",
    "def numpy_squared(data): return data ** 2 # ← Key! C-level inner loop": "def numpy_平方(data): return data ** 2 # ← 关键！C级内部循环",

    # === SLIDE 38 ===
    "Profiling experiment results": "性能分析实验结果",
    "4 operations + 3 experiments": "4种运算 + 3组实验",
    "Method": "方法",
    "Square operation": "平方运算",
    "Sumination operation": "求和运算",
    "Filtering": "过滤",
    "Speed ratio (compared to NumPy)": "速度比（与NumPy相比）",
    "for loop": "for循环",
    "~0.15s": "~0.15秒",
    "~0.05s": "~0.05秒",
    "~0.10s": "~0.10秒",
    "~75x slower": "慢约75倍",
    "List comprehension": "列表推导式",
    "~0.10s": "~0.10秒",
    "~0.07s": "~0.07秒",
    "~50x slower": "慢约50倍",
    "map()": "map()",
    "~0.12s": "~0.12秒",
    "~0.09s": "~0.09秒",
    "~60x slower": "慢约60倍",
    "NumPy vectorization": "NumPy向量化",
    "~0.002s": "~0.002秒",
    "~0.001s": "~0.001秒",
    "~0.003s": "~0.003秒",
    "Based on (1x)": "基准（1x）",
    "Key Lesson": "关键经验",
    "1. Be sure to use NumPy for numerical calculations (tens to hundreds of times difference)": "1. 数值计算务必使用NumPy（数十到数百倍的差距）",
    "2. In pure Python, list comprehension is the most efficient.": "2. 在纯Python中，列表推导式是最高效的。",
    "3. The larger the data, the greater the benefits of NumPy": "3. 数据量越大，NumPy的优势越明显",
    "4. map() is often slower than comprehension due to lambda overhead": "4. 由于lambda开销，map()通常比推导式慢",

    # === SLIDE 39 ===
    "SECTION 9": "第9节",
    "Practice: Data structure benchmark": "实践：数据结构基准测试",
    "Comparison of search/insert/delete performance of list, tuple, dict, and set": "list、tuple、dict和set的查找/插入/删除性能比较",

    # === SLIDE 40 ===
    "Practice Code: Comparing Search Performance": "实践代码：查找性能比较",
    "02_data_structures_benchmark.py": "02_data_structures_benchmark.py",
    "# Comparing Search Performance: Measuring the Real Difference in O(n) vs O(1)": "# 查找性能比较：测量O(n) vs O(1)的真实差异",
    "Sizes = [1000, 5000, 10000, 50000, 100000, 500000]": "数据规模 = [1000, 5000, 10000, 50000, 100000, 500000]",
    "for size in sizes:": "for size in 数据规模:",
    "list_data = list(range(size))": "list_data = list(range(size))",
    "dictionary_data = {x: x for x in range(size)}": "字典_data = {x: x for x in range(size)}",
    "set_data = set(range(size))": "set_data = set(range(size))",
    "Search values \u200b\u200b= [random.randint(size//2, size-1) for _ in range(100)]": "查找值 = [random.randint(size//2, size-1) for _ in range(100)]",
    "# list: O(n) - sequential search": "# list：O(n) - 顺序查找",
    "def list_navigation():": "def list_查找():",
    "for v in search values: _ = v in list_data": "for v in 查找值: _ = v in list_data",
    "# dict/set: O(1) - Instant lookup of hash table": "# dict/set：O(1) - 哈希表即时查找",
    "def set_search():": "def set_查找():",
    "for v in search values: _ = v in set_data": "for v in 查找值: _ = v in set_data",

    # === SLIDE 41 ===
    "Summary of benchmark results": "基准测试结果总结",
    "Overwhelming search performance of hash-based data structure": "基于哈希的数据结构的压倒性查找性能",
    "Operation": "操作",
    "Difference": "差异",
    "Search (500,000 items)": "查找（500,000项）",
    "~0.5s": "~0.5秒",
    "~0.00005s": "~0.00005秒",
    "~10,000x": "约10,000倍",
    "End insertion (100,000 items)": "末尾插入（100,000项）",
    "~0.005s (append)": "~0.005秒（append）",
    "~0.006s": "~0.006秒",
    "Similar": "相似",
    "Front insertion (10,000 items)": "前端插入（10,000项）",
    "~0.3s (insert)": "~0.3秒（insert）",
    "list Slow": "list较慢",
    "End deletion (10,000 items)": "末尾删除（10,000项）",
    "~0.001s (pop)": "~0.001秒（pop）",
    "~0.001s (del)": "~0.001秒（del）",
    "Prep deletion (10,000 items)": "前端删除（10,000项）",
    "~0.05s (pop(0))": "~0.05秒（pop(0)）",
    "Practical implications": "实际意义",
    "If membership checks(in) are frequent: use set or dict (O(1) vs O(n))": "如果成员检查（in）频繁：使用set或dict（O(1) vs O(n)）",
    "Larger data size: benefits of hash-based data structures are maximized": "数据量越大：基于哈希的数据结构优势越明显",
    "Memory: dict/set uses more memory due to hash table overhead (trade-off)": "内存：由于哈希表开销，dict/set占用更多内存（权衡）",

    # === SLIDE 42 ===
    "SECTION 10": "第10节",
    "Hands-on: Functional Programming ML": "实践：函数式编程ML",
    "map/filter/reduce, decorators, generators": "map/filter/reduce、装饰器、生成器",

    # === SLIDE 43 ===
    "map/filter/reduce data pipeline ||| Remove missing values (None)": "map/filter/reduce数据流水线 ||| 删除缺失值（None）",
    "03_functional_programming_ml.py": "03_functional_programming_ml.py",
    "Valid = list(filter(lambda x: list(map(lambda c: round(c * 9/5 + 32, 1), normal))": "有效 = list(filter(lambda x: list(map(lambda c: round(c * 9/5 + 32, 1), 正常))",
    "# Step 4: reduce → calculate statistics": "# 步骤4：reduce → 计算统计量",
    "sum = reduce(lambda acc, x: acc + x, normal)": "总和 = reduce(lambda acc, x: acc + x, 正常)",
    "원시_온도데이터[75] = None    # 결측값": "原始_温度数据[75] = None    # 缺失值",
    "# 단계 1: filter → 결측값(None) 제거": "# 步骤1：filter → 删除缺失值（None）",
    "유효 = list(filter(lambda x: x is not None, 원시_온도데이터))": "有效 = list(filter(lambda x: x is not None, 原始_温度数据))",
    "# 단계 2: filter → 이상값 제거 (0~50도 범위)": "# 步骤2：filter → 删除异常值（0~50度范围）",
    "정상 = list(filter(lambda x: 0 <= x <= 50, 유효))": "正常 = list(filter(lambda x: 0 <= x <= 50, 有效))",
    "# 단계 3: map → 섭씨 → 화씨 변환": "# 步骤3：map → 摄氏 → 华氏转换",
    "화씨 = list(map(lambda c: round(c * 9/5 + 32, 1), 정상))": "华氏 = list(map(lambda c: round(c * 9/5 + 32, 1), 正常))",
    "# 단계 4: reduce → 통계량 계산": "# 步骤4：reduce → 计算统计量",
    "from functools import reduce": "from functools import reduce",
    "합계 = reduce(lambda acc, x: acc + x, 정상)": "总和 = reduce(lambda acc, x: acc + x, 正常)",

    # === SLIDE 44 ===
    "Decorator & Generator Pattern": "装饰器与生成器模式",
    "Function expansion and memory-efficient data loading": "函数扩展与内存高效的数据加载",
    "# Decorator: Function extension": "# 装饰器：函数扩展",
    "def Timing (function):": "def 计时(函数):",
    "@functools.wraps(function)": "@functools.wraps(函数)",
    "def wrapper(*args, **kwargs):": "def wrapper(*args, **kwargs):",
    "result = function(*args, **kwargs)": "result = 函数(*args, **kwargs)",
    "print(f'{function.__name__}: {end-start:.4f} seconds')": "print(f'{函数.__name__}：{end-start:.4f}秒')",
    "return result": "return result",
    "return wrapper": "return wrapper",
    "@timing": "@计时",
    "def data_preprocessing(data):": "def 数据预处理(data):",
    "# Measure execution time automatically!": "# 自动测量执行时间！",
    "return [x for x in data if x > 0]": "return [x for x in data if x > 0]",
    "# generator: batch data loader": "# 生成器：批量数据加载器",
    "def batch_loader(data, batchsize=32):": "def batch_loader(data, batchsize=32):",
    "index = list(range(len(data)))": "index = list(range(len(data)))",
    "random.shuffle(index)": "random.shuffle(index)",
    "for start in range(0, len(index), batch size):": "for start in range(0, len(index), 批量大小):",
    "batch = index[start:start+batchsize]": "batch = index[start:start+batchsize]",
    "yield [data[i] for i in batch]": "yield [data[i] for i in batch]",
    "# use: do not load entire into memory": "# 使用：不将全部数据加载到内存",
    "for batch in batch_loader(data, 32):": "for batch in batch_loader(data, 32):",
    "Learning (batch) # Batch unit learning": "训练(batch) # 按批次训练",
    "@lru_cache: Memoization": "@lru_cache：记忆化",
    "@functools.lru_cache(maxsize=128)": "@functools.lru_cache(maxsize=128)",
    "def Fibonacci(n): ... # O(2^n) → O(n)": "def 斐波那契(n): ... # O(2^n) → O(n)",

    # === SLIDE 45 ===
    "Function Composition": "函数组合",
    "Functional version of sklearn Pipeline": "sklearn Pipeline的函数式版本",
    "def Pipeline (*functions):": "def 流水线(*函数列表):",
    '"""Pipeline for sequentially synthesizing functions"""': '"""按顺序组合函数的流水线"""',
    "def composite_function(input):": "def 组合函数(输入):",
    "result = input": "result = 输入",
    "for function in functions:": "for 函数 in 函数列表:",
    "result = function(result)": "result = 函数(result)",
    "return result": "return result",
    "return composition_function": "return 组合函数",
    "# Preprocessing functions": "# 预处理函数",
    "def missing_value_removal(d): return [x for x in d if x]": "def 缺失值删除(d): return [x for x in d if x]",
    "def outlier_removal(d): return [x for standardization)": "def 异常值删除(d): return [x for 标准化)",
    "Results = ML_preprocessing (raw_data)": "结果 = ML_预处理(原始数据)",
    "    μ = sum(d)/len(d)": "    μ = sum(d)/len(d)",
    "    σ = (sum((x-μ)**2 for x in d)/len(d))**0.5": "    σ = (sum((x-μ)**2 for x in d)/len(d))**0.5",
    "    return [(x-μ)/σ for x in d]": "    return [(x-μ)/σ for x in d]",
    "# Input: 100 → Missing removal → Outlier removal → Standardization": "# 输入：100 → 缺失值删除 → 异常值删除 → 标准化",
    "Functional programming essentials": "函数式编程要点",
    "map(): Data conversion (1:1 mapping)": "map()：数据转换（1:1映射）",
    "filter(): Data filtering (conditional selection)": "filter()：数据过滤（条件筛选）",
    "reduce(): Aggregation (list → single value)": "reduce()：聚合（列表 → 单一值）",
    "Decorator: @Timing, @logging, @lru_cache": "装饰器：@计时、@日志、@lru_cache",
    "Generator: yield-based batch loading, memory saving": "生成器：基于yield的批量加载，节省内存",
    "Function synthesis: functional version of sklearn Pipeline": "函数组合：sklearn Pipeline的函数式版本",
    "데코레이터: @타이밍, @로깅, @lru_cache": "装饰器：@计时、@日志、@lru_cache",
    "제너레이터: yield 기반 배치 로딩, 메모리 절약": "生成器：基于yield的批量加载，节省内存",
    "함수 합성: sklearn Pipeline의 함수형 버전": "函数组合：sklearn Pipeline的函数式版本",

    # === SLIDE 46 ===
    "SECTION 11": "第11节",
    "End-to-end ML pipeline": "端到端ML流水线",
    "Implementing a KNN classifier in pure Python": "用纯Python实现KNN分类器",

    # === SLIDE 47 ===
    "Pure Python KNN Classifier": "纯Python KNN分类器",
    "5-stage ML pipeline without external libraries": "不使用外部库的5阶段ML流水线",
    "Step 1: Data generation": "步骤1：数据生成",
    "Synthetic 2D data": "合成2D数据",
    "Class 0: Centroid (2,2)": "类别0：质心 (2,2)",
    "Class 1: Centroid (5,5)": "类别1：质心 (5,5)",
    "100 each, 200 total": "每类100个，共200个",
    "Step 2: Preprocessing": "步骤2：预处理",
    "Min-Max normalization": "Min-Max归一化",
    "x' = (x-min)/(max-min)": "x' = (x-min)/(max-min)",
    "All features Unify scale to 0~1": "所有特征统一缩放到0~1",
    "Step 3: Split": "步骤3：分割",
    "Train/Test Split": "训练/测试分割",
    "80% training, 20% test": "80%训练，20%测试",
    "test_ratio = 0.2": "test_ratio = 0.2",
    "random.shuffle()": "random.shuffle()",
    "Step 4: Implement KNN": "步骤4：实现KNN",
    "Calculate Euclidean distance": "计算欧几里得距离",
    "Select k nearest neighbors": "选择k个最近邻",
    "Predict by majority vote": "通过多数投票预测",
    "Compare k=1,3,5,7,9": "比较k=1,3,5,7,9",
    "Step 5: Evaluation": "步骤5：评估",
    "Accuracy (Accuracy)": "准确率（Accuracy）",
    "Precision (Precision)": "精确率（Precision）",
    "Recall": "召回率",
    "재현율 (Recall)": "召回率（Recall）",
    "F1-score": "F1分数",

    # === SLIDE 48 ===
    "Core code: KNN classifier implementation": "核心代码：KNN分类器实现",
    "Euclidean distance + majority voting": "欧几里得距离 + 多数投票",
    "def euclidean_distance(a, b):": "def euclidean_distance(a, b):",
    '"""Euclidean distance calculation"""': '"""欧几里得距离计算"""',
    "    return math.sqrt(": "    return math.sqrt(",
    "        sum((ai-bi)**2 for ai,bi in zip(a,b)))": "        sum((ai-bi)**2 for ai,bi in zip(a,b)))",
    "def knn_predict(X_train, y_train, x_query, k=5):": "def knn_predict(X_train, y_train, x_query, k=5):",
    '"""KNN prediction: Majority vote of k nearest neighbors"""': '"""KNN预测：k个最近邻的多数投票"""',
    "    distances = [": "    distances = [",
    "        (euclidean_distance(x_query, x_tr), label)": "        (euclidean_distance(x_query, x_tr), label)",
    "        for x_tr, label": "        for x_tr, label",
    "        in zip(X_train, y_train)]": "        in zip(X_train, y_train)]",
    "    distances.sort(key=lambda x: x[0])": "    distances.sort(key=lambda x: x[0])",
    "    k_nearest = distances[:k]": "    k_nearest = distances[:k]",
    "    votes = [label for _, label in k_nearest]": "    votes = [label for _, label in k_nearest]",
    "    return max(set(votes), key=votes.count)": "    return max(set(votes), key=votes.count)",
    "Chapter 2 Concept mapping used": "第2章使用的概念映射",
    "Data generation → function, list, for loop": "数据生成 → 函数、列表、for循环",
    "Preprocessing → list comprehension, min/max": "预处理 → 列表推导式、min/max",
    "Splitting → slicing, random.shuffle()": "分割 → 切片、random.shuffle()",
    "KNN → lambda, sorted(), zip(), tuple": "KNN → lambda、sorted()、zip()、tuple",
    "Evaluation → f-string, arithmetic Operation ||": "评估 → f-string、算术运算 ||",
    "수식: d(x,y) = √Σ(xi - yi)²": "公式：d(x,y) = √Σ(xi - yi)²",
    "k값별 성능 비교:": "各k值性能比较：",
    "k=1: 노이즈에 민감 (과적합)": "k=1：对噪声敏感（过拟合）",
    "k=5: 적절한 일반화": "k=5：适当的泛化",
    "k=9: 과도한 평활화 (과소적합)": "k=9：过度平滑（欠拟合）",

    # === SLIDE 49 ===
    "SECTION 12": "第12节",
    "Key Summary + Review Questions": "核心总结 + 复习问题",
    "Summary of Chapter 2": "第2章总结",

    # === SLIDE 50 ===
    "Key Summary Table": "核心总结表",
    "All concepts learned in Chapter 2": "第2章学习的所有概念",
    "Topics": "主题",
    "Key content": "关键内容",
    "Why Python": "为什么选择Python",
    "Adhesive language + rich ecosystem + low barrier to entry": "胶水语言 + 丰富的生态系统 + 低入门门槛",
    "Data types": "数据类型",
    "int, float, str, bool + dynamic typing": "int、float、str、bool + 动态类型",
    "List/tuple": "列表/元组",
    "mutable vs immutable, slicing, O(1) approach": "可变 vs 不可变，切片，O(1)访问",
    "Dictionary/Set": "字典/集合",
    "Hash-based O(1) navigation, hyperparameter management": "基于哈希的O(1)查找，超参数管理",
    "function": "函数",
    "def, lambda, *args, **kwargs, multiple returns": "def、lambda、*args、**kwargs、多返回值",
    "class": "类",
    "fit/predict/transform pattern = sklearn API": "fit/predict/transform模式 = sklearn API",
    "Profiling → NumPy vectorization → GIL bypass": "性能分析 → NumPy向量化 → GIL绕过",
    "conda/venv + Jupyter (exploration) + IDE (production)": "conda/venv + Jupyter（探索） + IDE（生产）",

    # === SLIDE 51 ===
    "Summary of formulas": "公式总结",
    "Key formulas that appeared in Chapter 2": "第2章出现的关键公式",
    "Euclidean Distance": "欧几里得距离",
    "d(x, y) = sqrt( Σ (xi - yi)² )": "d(x, y) = sqrt( Σ (xi - yi)² )",
    "Basics of distance-based algorithms such as KNN and K-Means": "KNN和K-Means等基于距离的算法基础",
    "Min-Max normalization": "Min-Max归一化",
    "x' = (x - x_min) / (x_max - x_min)": "x' = (x - x_min) / (x_max - x_min)",
    "Conversion of all features to the range [0, 1]": "将所有特征转换到[0, 1]范围",
    "Z-score standardization": "Z-score标准化",
    "z = (x - μ) / σ": "z = (x - μ) / σ",
    "Conversion to mean = 0, standard deviation = 1": "转换为均值=0，标准差=1",
    "Accuracy": "准确率",
    "Acc = (TP + TN) / (TP + TN + FP + FN)": "Acc = (TP + TN) / (TP + TN + FP + FN)",
    "Correct among all predictions percentage of predictions": "所有预测中正确预测的比例",

    # === SLIDE 52 ===
    "Review questions (1/2)": "复习问题（1/2）",
    "Check theory + practice": "检验理论 + 实践",
    "Q1. What is dynamic typing? What are the pros and cons of ML development compared to static typing?": "Q1. 什么是动态类型？与静态类型相比，在ML开发中有什么优缺点？",
    "Q2. Why is 0.1 + 0.2 == 0.3 False? How to deal with it in ML?": "Q2. 为什么0.1 + 0.2 == 0.3是False？在ML中如何处理？",
    "Q3. Why is list.append() O(1) and insert(0) O(n)?": "Q3. 为什么list.append()是O(1)而insert(0)是O(n)？",
    "Q4. Membership check on 1 million data: Why choose list vs set?": "Q4. 对100万数据进行成员检查：为什么选择list vs set？",
    "Q5. Why not call fit() on test data? (data leak)": "Q5. 为什么不能在测试数据上调用fit()？（数据泄露）",

    # === SLIDE 53 ===
    "Review questions (2/2)": "复习问题（2/2）",
    "Coding + Advanced": "编程 + 进阶",
    "Q6. What is the result of [x**2 for x in range(10) if x%3==0]?": "Q6. [x**2 for x in range(10) if x%3==0]的结果是什么？",
    "Q7. Three reasons why NumPy vectorization is tens to hundreds of times faster than for loops?": "Q7. NumPy向量化比for循环快数十到数百倍的3个原因？",
    "Q8. What is GIL? How to do CPU parallel processing in ML?": "Q8. 什么是GIL？在ML中如何进行CPU并行处理？",
    "Q9. Memory saving principles of generators and utilization of ML batch loading?": "Q9. 生成器的内存节省原理以及ML批量加载的应用？",
    "Q10. Remove missing values \u200b\u200b→ Clipping to negative 0 → 2x scaling": "Q10. 删除缺失值 → 负值截断为0 → 2倍缩放",
    "Implement map/filter and list comprehension respectively.": "分别用map/filter和列表推导式实现。",

    # === SLIDE 54 ===
    "Thank You": "谢谢",
    "Chapter 2: Python for machine learning": "第2章：机器学习中的Python",
    "Next chapter: NumPy & Pandas in depth": "下一章：NumPy与Pandas深入讲解",

    # Section numbers that repeat
    "SECTION 8": "第8节",
    "SECTION 9": "第9节",
    "SECTION 10": "第10节",
    "SECTION 11": "第11节",
    "SECTION 12": "第12节",

    # Additional Korean texts found
    "High": "高",
    "1. 제너레이터 배치 로딩 (yield)": "1. 生成器批量加载（yield）",
    "2. np.memmap (디스크 매핑 배열)": "2. np.memmap（磁盘映射数组）",
    "4. float64 → float32 다운캐스팅": "4. float64 → float32降精度",
    "모두 fit() → predict() → score() 지원": "全部支持fit() → predict() → score()",
}


def translate_text(text):
    """Translate text using the dictionary. Return original if no translation found."""
    stripped = text.strip()
    if stripped in TRANSLATIONS:
        # Preserve leading/trailing whitespace
        leading = text[:len(text) - len(text.lstrip())]
        trailing = text[len(text.rstrip()):]
        return leading + TRANSLATIONS[stripped] + trailing
    return text


def process_text_frame(text_frame):
    """Process all paragraphs in a text frame."""
    for para in text_frame.paragraphs:
        for run in para.runs:
            if run.text.strip():
                run.text = translate_text(run.text)


def main():
    input_path = '2장_머신러닝을_위한_파이썬_강의PPT_확장_eng.pptx'
    output_path = '2장_머신러닝을_위한_파이썬_강의PPT_확장_chz.pptx'

    print(f"Loading: {input_path}")
    prs = Presentation(input_path)

    translated_count = 0
    untranslated = set()

    for slide_idx, slide in enumerate(prs.slides):
        # Process shapes
        for shape in slide.shapes:
            if shape.has_text_frame:
                for para in shape.text_frame.paragraphs:
                    for run in para.runs:
                        stripped = run.text.strip()
                        if stripped:
                            if stripped in TRANSLATIONS:
                                run.text = translate_text(run.text)
                                translated_count += 1
                            else:
                                untranslated.add(stripped)

            # Process tables
            if shape.has_table:
                for row in shape.table.rows:
                    for cell in row.cells:
                        if cell.text_frame:
                            for para in cell.text_frame.paragraphs:
                                for run in para.runs:
                                    stripped = run.text.strip()
                                    if stripped:
                                        if stripped in TRANSLATIONS:
                                            run.text = translate_text(run.text)
                                            translated_count += 1
                                        else:
                                            untranslated.add(stripped)

        # Process notes
        if slide.has_notes_slide:
            for para in slide.notes_slide.notes_text_frame.paragraphs:
                for run in para.runs:
                    stripped = run.text.strip()
                    if stripped:
                        if stripped in TRANSLATIONS:
                            run.text = translate_text(run.text)
                            translated_count += 1
                        else:
                            untranslated.add(stripped)

    prs.save(output_path)
    print(f"\nSaved: {output_path}")
    print(f"Translated segments: {translated_count}")
    print(f"Untranslated unique segments: {len(untranslated)}")

    if untranslated:
        print("\n--- Untranslated segments (first 30) ---")
        for i, t in enumerate(sorted(untranslated)[:30]):
            print(f"  {t[:100]}")


if __name__ == '__main__':
    main()
